# Generated by Django 2.0.5 on 2018-05-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180524_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together={('sender', 'receiver')},
        ),
    ]
