# Generated by Django 2.0.4 on 2018-05-27 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pending_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_meetup',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pending_meetup',
            name='guest',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pending_meetup',
            name='host',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pending_meetup',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
