# Generated by Django 2.0.5 on 2018-05-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180527_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_meetup',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted')], default='p', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pending_meetup',
            unique_together={('host', 'guest')},
        ),
    ]
