# Generated by Django 2.0.5 on 2018-05-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180528_0526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pending_meetup',
            unique_together=set(),
        ),
    ]
