# Generated by Django 2.0.5 on 2018-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180528_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_meetup',
            name='date',
            field=models.DateField(help_text='Format yyyy-mm-dd'),
        ),
    ]
