# Generated by Django 2.0.4 on 2018-05-04 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='dob',
            field=models.DateField(help_text='Format yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user_profile.ExtUser'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user_profile.ExtUser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='user_profile.ExtUser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='user_profile.ExtUser'),
        ),
        migrations.AlterField(
            model_name='pending_meetup',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='user_profile.ExtUser'),
        ),
        migrations.AlterField(
            model_name='pending_meetup',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='user_profile.ExtUser'),
        ),
    ]
